### ISSUE TITLE
Better Obfuscator

### ISSUE THREAD

**Issue by mateokladaric** [efrederickson/XFuscator#10]
Better obfuscators: Synapse Xen, Luraph

for example Synapse Xen Options:

reduced: Reduces the amount of obfuscation in the Synapse Xen VM. Improves performance at the cost of some security.
disableintegrity: Disables VM integrity protection. If your script crashes/freezes after protection, enable this option.
BETA: constants: Protects the constants of your script. print("hello"), "hello" will not be visible if someone dumps the constants of your script.
BETA: constants-ex: Protects the constants of your script, including table indexes. game.Workspace.Name = "asd", Workspace will also be obfuscated with "asd".
bytecode: Transforms the Synapse Xen VM into a bytecode format that is hard to decompile. Makes your script only work on Synapse and other similar pieces of software.
antiaxon: Any axon based software which tries to run this script will crash. Also protects against game developers trying to sandbox the script.

**Comment by Robotniks** [comment]
look at the date this repo was made
